// Generated by wxt
export {}
declare global {
  const AnimatedNumberBadge: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/AnimatedNumberBadge').AnimatedNumberBadge
  const CommandPagination: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/TabCommand').CommandPagination
  const ConditionalWrapper: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/ConditionalWrapper').ConditionalWrapper
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const DynamicViewportVarsSetter: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/hooks/useDynamicViewportVars').DynamicViewportVarsSetter
  const EchoItem: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/EchoItem').default
  const Favicon: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/TabItem').Favicon
  const FilterTagChips: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/FilterTagChips').default
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const KeyboardShortcut: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/KeyboardShortcut').KeyboardShortcut
  const KeyboardShortcutKey: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/KeyboardShortcut').KeyboardShortcutKey
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const MobileBottomBar: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/MobileBottomBar').default
  const MobileBottomBarPortal: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/MobileBottomBar').MobileBottomBarPortal
  const NumberNotificationBadge: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/NumberNotificationBadge').NumberNotificationBadge
  const OnClose: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/TabCommand').OnClose
  const ScrollTopFAB: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/ScrollTopFAB').default
  const SelectableItem: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/SelectableList').SelectableItem
  const SelectableList: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/SelectableList').SelectableList
  const SnapshotPreview: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/SnapshotPreview').default
  const SortButton: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/SortButton').default
  const TabCommandDialog: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/TabCommand').TabCommandDialog
  const TabItem: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/TabItem').default
  const Waveform: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/Waveform').Waveform
  const browser: typeof import('wxt/browser').browser
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const dvh100: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/hooks/useDynamicViewportVars').dvh100
  const dvw100: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/hooks/useDynamicViewportVars').dvw100
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const getDynamicViewportVars: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/hooks/useDynamicViewportVars').getDynamicViewportVars
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const storage: typeof import('wxt/utils/storage').storage
  const updateViewport: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/hooks/useDynamicViewportVars').updateViewport
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDialogState: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/TabCommand').useDialogState
  const useDynamicViewportVars: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/hooks/useDynamicViewportVars').default
  const useEffect: typeof import('react').useEffect
  const useGridLayoutInfo: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/hooks/useGridLayoutInfo').default
  const useIsFirstRender: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/hooks/useIsFirstRender').default
  const useMemo: typeof import('react').useMemo
  const usePatternBackground: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/hooks/usePatternBackground').default
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
  const useTabCommand: typeof import('/Users/rpavlini/projects/echotab/apps/extension/src/components/TabCommand').useTabCommand
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { NumberNotificationBadgeProps } from '/Users/rpavlini/projects/echotab/apps/extension/src/components/NumberNotificationBadge'
  import('/Users/rpavlini/projects/echotab/apps/extension/src/components/NumberNotificationBadge')
  // @ts-ignore
  export type { TabCommandDialogRef } from '/Users/rpavlini/projects/echotab/apps/extension/src/components/TabCommand'
  import('/Users/rpavlini/projects/echotab/apps/extension/src/components/TabCommand')
  // @ts-ignore
  export type { PatternType } from '/Users/rpavlini/projects/echotab/apps/extension/src/hooks/usePatternBackground'
  import('/Users/rpavlini/projects/echotab/apps/extension/src/hooks/usePatternBackground')
}
