// Generated by wxt
// Types for the #import virtual module
declare module '#imports' {
  export { browser, Browser } from 'wxt/browser';
  export { storage, StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage';
  export { useAppConfig } from 'wxt/utils/app-config';
  export { ContentScriptContext, WxtWindowEventMap } from 'wxt/utils/content-script-context';
  export { createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe';
  export { createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated';
  export { createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root';
  export { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types';
  export { defineAppConfig, WxtAppConfig } from 'wxt/utils/define-app-config';
  export { defineBackground } from 'wxt/utils/define-background';
  export { defineContentScript } from 'wxt/utils/define-content-script';
  export { defineUnlistedScript } from 'wxt/utils/define-unlisted-script';
  export { defineWxtPlugin } from 'wxt/utils/define-wxt-plugin';
  export { injectScript, ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script';
  export { InvalidMatchPattern, MatchPattern } from 'wxt/utils/match-patterns';
  export { useState, useCallback, useMemo, useEffect, useRef, useContext, useReducer } from 'react';
  export { fakeBrowser } from 'wxt/testing';
  export { AnimatedNumberBadge } from '../src/components/AnimatedNumberBadge';
  export { ConditionalWrapper } from '../src/components/ConditionalWrapper';
  export { default as EchoItem } from '../src/components/EchoItem';
  export { default as FilterTagChips } from '../src/components/FilterTagChips';
  export { KeyboardShortcut, KeyboardShortcutKey } from '../src/components/KeyboardShortcut';
  export { default as MobileBottomBar, MobileBottomBarPortal } from '../src/components/MobileBottomBar';
  export { NumberNotificationBadge, NumberNotificationBadgeProps } from '../src/components/NumberNotificationBadge';
  export { default as ScrollTopFAB } from '../src/components/ScrollTopFAB';
  export { SelectableList, SelectableItem } from '../src/components/SelectableList';
  export { default as SnapshotPreview } from '../src/components/SnapshotPreview';
  export { default as SortButton } from '../src/components/SortButton';
  export { useDialogState, OnClose, useTabCommand, CommandPagination, TabCommandDialog, TabCommandDialogRef } from '../src/components/TabCommand';
  export { default as TabItem, Favicon } from '../src/components/TabItem';
  export { Waveform } from '../src/components/Waveform';
  export { default as useDynamicViewportVars, updateViewport, getDynamicViewportVars, DynamicViewportVarsSetter, dvh100, dvw100 } from '../src/hooks/useDynamicViewportVars';
  export { default as useGridLayoutInfo } from '../src/hooks/useGridLayoutInfo';
  export { default as useIsFirstRender } from '../src/hooks/useIsFirstRender';
  export { default as usePatternBackground, PatternType } from '../src/hooks/usePatternBackground';
}
