/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Links {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  localId: string;
  title: string | null;
  url: string;
}

export interface Lists {
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  importCount: Generated<Int8>;
  localId: string;
  ogimageurl: string | null;
  ownerId: string;
  profileLinkUrl: string | null;
  publicId: Generated<string>;
  published: Generated<boolean>;
  title: string | null;
  updated_at: Generated<Timestamp>;
  viewCount: Generated<Int8>;
}

export interface ListsLinks {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  linkId: Int8;
  listId: Int8;
}

export interface DB {
  links: Links;
  lists: Lists;
  lists_links: ListsLinks;
}
