name: Fly Deploy
on:
  push:
    branches:
      - main
    paths:
      - "src/apps/web/**"
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: fly deploy --config fly.web.toml --dockerfile web.Dockerfile --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_TOKEN }}
